package com.twentyfourseven.util

enum class AnalyticsEvent {
    NAV_DRAWER_CLICKED,
    HOME_GIZMO_CLICKED,
    HOME_CONNECT_CLICKED,
    HOME_DRIBBLE_CLICKED,
    DRAWER_T_AND_C_CLICKED,
    DRAWER_PRIVACY_POLICY_CLICKED,
    DRAWER_RATE_US_CLICKED,
    DRAWER_SHARE_CLICKED,
    GIZMO_FIRST_TAP,
    GIZMO_SOUND_PLAY_CLICKED
}